spring:
  application.name: auth

server:
  port: 9000

locky:
  services:
    client:
      url: http://localhost:9001
    user:
      url: http://localhost:9002

database:
  endpoint: localhost:5432
  name: demo
  username: database_username
  password: database_password